export default {
    LOGIN:"LOGIN",
    LOGOUT:"LOGOUT",
    SIGNUP:"SIGNUP",
    CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
    NO_INTERNET: 'NO_INTERNET',
    LOADING_START:'LOADING_START',
    GET_USER_PRODUCTS:'GET_USER_PRODUCTS',
    ERROR:'ERROR'
}